//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleRole
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int RuleId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Rule Rule { get; set; }
    }
}
